apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image:  {{ .Values.image.name}} 
          ports:
            - containerPort: 8090
--- 
apiVersion: v1
kind: Service
metadata:
  name: cs
spec:
  selector:
    app: {{ .Values.appName }}
  ports:
    - port: 8090
      targetPort: 8090
  type: LoadBalancer